export const HELP_RETRIEVAL_CASES = [
  { question: "What are the main tabs in the app?", expectedId: "app-overview" },
  { question: "How do I start reading again from Library?", expectedId: "start-reading" },
  { question: "How do I add a book manually?", expectedId: "add-book" },
  { question: "How does Search a book work?", expectedId: "search-book" },
  { question: "What buttons are on a Library book tile?", expectedId: "library" },
  { question: "How do I change the author photo?", expectedId: "author" },
  { question: "What is Journey Timeline?", expectedId: "chapters" },
  { question: "What is inside a chapter detail screen?", expectedId: "chapter-detail" },
  { question: "Where is Hear the story?", expectedId: "story-recap" },
  { question: "What does the reading screen look like?", expectedId: "session-overview" },
  { question: "What do all the reading dock buttons do?", expectedId: "session-buttons" },
  { question: "How do I mute the microphone while reading?", expectedId: "session-mic" },
  { question: "How do I use Tap to ask or Hands-free?", expectedId: "session-buttons" },
  { question: "How can I ask if automatic listening misses me?", expectedId: "session-mic" },
  { question: "How do page snapshots work when I turn the page?", expectedId: "camera-options" },
  { question: "Does the companion keep story context after a new snapshot?", expectedId: "camera-options" },
  { question: "How do I bring the reading chat back on topic?", expectedId: "session-transcript" },
  { question: "What is Ghost mode?", expectedId: "ghost-mode" },
  { question: "What is the progress card at the top of reading?", expectedId: "session-progress" },
  { question: "What is Done in this session?", expectedId: "session-activity" },
  { question: "How do I end the reading session?", expectedId: "session-end" },
  { question: "What can the companion do by voice?", expectedId: "voice-commands" },
  { question: "How do I save and review vocabulary words?", expectedId: "vocabulary" },
  { question: "What is on the Home screen?", expectedId: "dashboard" },
  { question: "How do the Home charts and Continue reading cards work?", expectedId: "dashboard-charts" },
  { question: "What is the Revisit these card?", expectedId: "recall-card" },
  { question: "How does the streak work?", expectedId: "streak" },
  { question: "How do saved quotes work?", expectedId: "gems" },
  { question: "How do I generate an illustration for a gem?", expectedId: "gem-detail" },
  { question: "How do I choose a gem card template, accent and aspect ratio?", expectedId: "gem-detail" },
  { question: "What is in Memory?", expectedId: "memory" },
  { question: "Explain the Cognitive Constellation mind map", expectedId: "mind-map" },
  { question: "How do I change my avatar and companion?", expectedId: "profile" },
  { question: "Where can I copy my Profile UID?", expectedId: "profile" },
  { question: "How do I sign in with Google and sync my account?", expectedId: "account-sync" },
  { question: "What can I change in Settings?", expectedId: "settings" },
  { question: "Why is there a 30 minute reading limit?", expectedId: "daily-reading-limit" },
  { question: "How do I request more reading time and what does the email include?", expectedId: "daily-reading-limit" },
  { question: "How can I restore a book from the trash?", expectedId: "delete-restore-books" },
  { question: "How do privacy, backup and delete data work?", expectedId: "settings-data" },
  { question: "How do push notifications and study reminders work?", expectedId: "notifications" },
  { question: "How do I check for app updates and release notes?", expectedId: "updates" },
  { question: "Are production deployment announcement pushes sent automatically to opted-in readers?", expectedId: "updates" },
  { question: "How do I report a bug and track its status?", expectedId: "report-issue" },
  { question: "What data does Help & Support send to AI?", expectedId: "help-privacy" },
  { question: "How does the welcome tour work?", expectedId: "onboarding" },
  { question: "What should I do if the mic or camera is not working?", expectedId: "troubleshooting" },
  { question: "What is on the About screen?", expectedId: "about" },
  { question: "What is Reader Arena?", expectedId: "reader-arena" },
  { question: "Which update introduced Google sign-in?", expectedId: "release-2-0-0" },
  { question: "Which update introduced Reader Arena?", expectedId: "release-2-4-0" },
  { question: "What did version 2.5.0 Every Line, Reimagined add?", expectedId: "release-2-5-0" },
  { question: "Which version added push notifications?", expectedId: "release-2-1-0" },
  { question: "Which update added Search a book improvements and edition choices?", expectedId: "release-2-2-0" },
  { question: "Show me the release history", expectedId: "release-history" },
];

export const HELP_FEATURE_MANIFEST = [
  {
    name: "bottom navigation",
    entryId: "app-overview",
    files: ["App.jsx"],
    includes: ["goDashboard", "goLibrary", "goGems", "goMemory", "onNavigate(\"profile\")"],
  },
  {
    name: "manual add book modal",
    entryId: "add-book",
    files: ["App.jsx", "components/BookSearchFlow.jsx"],
    includes: ["Add a book", "Add manually", "mode=\"manual\"", "Who wrote this book?", "Upload the book&apos;s contents page", "Skip, I&apos;ll add chapters manually", "Review chapters"],
  },
  {
    name: "search a book flow",
    entryId: "search-book",
    files: ["components/BookSearchFlow.jsx"],
    includes: ["Search a book", "Finding the book", "Add to library", "Read contents", "Add manually"],
  },
  {
    name: "library book tile controls",
    entryId: "library",
    files: ["BookTile.jsx"],
    includes: ["Author", "aria-label=\"Start reading\"", "aria-label=\"Delete book\""],
  },
  {
    name: "pre-session hear the story",
    entryId: "story-recap",
    files: ["App.jsx", "BookTile.jsx"],
    includes: ["Hear the story", "Start Reading", "onPlay={() => nav.openRecap(b.id)}"],
  },
  {
    name: "author sheet",
    entryId: "author",
    files: ["App.jsx"],
    includes: ["Find photo online", "Look up again", "Author details", "Save"],
  },
  {
    name: "chapter tabs",
    entryId: "chapters",
    files: ["App.jsx"],
    includes: ["Journey Timeline", "Chapters", "chapter-card-status-pill"],
  },
  {
    name: "chapter detail and vocab",
    entryId: "chapter-detail",
    files: ["App.jsx"],
    includes: ["Summary", "Vocabulary", "Context", "Analysis", "Practiced"],
  },
  {
    name: "reading dock buttons",
    entryId: "session-buttons",
    files: ["App.jsx"],
    includes: ["\"Stop asking\" : \"Ask a question\"", "aria-label=\"Toggle transcript\"", "aria-label=\"End session\""],
  },
  {
    name: "snapshot and printed page controls",
    entryId: "camera-options",
    files: ["App.jsx"],
    includes: ["aria-label={snapshot ?", "Next page", "Share a snapshot of the page"],
  },
  {
    name: "page verification safety flow",
    entryId: "camera-options",
    files: ["App.jsx", "sessionPage.js", "../../backend/server.js"],
    includes: ["/api/reading/verify-page", "pageStatus: pageCanBeSentToLive", "Retake", "pageCanBeSentToLive"],
  },
  {
    name: "ghost mode toggle",
    entryId: "ghost-mode",
    files: ["App.jsx"],
    includes: ["Toggle Author's Ghost Mode", "Channeling the Author's Persona"],
  },
  {
    name: "session activity sheet",
    entryId: "session-activity",
    files: ["App.jsx"],
    includes: ["Done in this session", "Nothing yet. Saved words, gems and chapter updates will show up here."],
  },
  {
    name: "dashboard cards and continue reading",
    entryId: "dashboard",
    files: ["App.jsx"],
    includes: ["Vocabulary growth", "Overall progress", "Gems this week", "Continue reading"],
  },
  {
    name: "gems detail and download",
    entryId: "gem-detail",
    files: ["App.jsx", "GemStoryCard.jsx"],
    includes: ["Generate illustration", "Real-life application", "Download"],
  },
  {
    name: "mind map controls",
    entryId: "mind-map",
    files: ["MemoryConstellation.jsx"],
    includes: ["Cognitive Constellation", "Rebuild connections", "Surprise me", "Echoes in other books"],
  },
  {
    name: "profile avatar cropper and picker",
    entryId: "profile",
    files: ["App.jsx", "AvatarCropper.jsx"],
    includes: ["Change avatar", "Remove photo", "Crop your photo", "Save photo"],
  },
  {
    name: "google account gate",
    entryId: "account-sync",
    files: ["AccountGate.jsx"],
    includes: ["Continue with Google", "Use account copy", "Keep this device's copy", "Sign out"],
  },
  {
    name: "settings sections",
    entryId: "settings",
    files: ["SettingsScreens.jsx"],
    includes: ["Daily reading goal", "Appearance", "Companion voice", "Preview this voice", "Notifications", "Reading limit"],
  },
  {
    name: "privacy backup danger zone",
    entryId: "settings-data",
    files: ["SettingsScreens.jsx"],
    includes: ["Clear conversation history", "Clear saved preferences", "Deleted books", "Export backup", "Restore", "Delete all my data"],
  },
  {
    name: "deleted books recovery bin",
    entryId: "delete-restore-books",
    files: ["SettingsScreens.jsx", "App.jsx"],
    includes: ["Deleted books", "Open deleted-books bin", "Restore", "permanentlyDeleteBook", "moved to Settings"],
  },
  {
    name: "account reading allowance",
    entryId: "daily-reading-limit",
    files: ["readingQuota.js", "SettingsScreens.jsx", "../../backend/server.js", "../../supabase/migrations/20261014120000_add_account_reading_limits.sql"],
    includes: ["recordReadingUsage", "dailyLimitMinutes", "SESSION_LIMIT_ADMIN_USER_IDS", "record_reading_companion_session_usage"],
  },
  {
    name: "continuous voice listening",
    entryId: "session-mic",
    files: ["App.jsx", "voiceIntent.js"],
    includes: ["VOICE LISTENING POLICY", "classifyVoiceIntent", "Quiet reading · still listening"],
  },
  {
    name: "snapshot workflow animation",
    entryId: "camera-options",
    files: ["helpAnimations.js", "HelpAnimations.jsx"],
    includes: ["session-snapshot-flow", "Snapshot reading", "ChevronRight"],
  },
  {
    name: "snapshot-only welcome tour",
    entryId: "onboarding",
    files: ["onboarding/Onboarding.jsx", "onboarding/OnboardingScenes.jsx"],
    includes: ["snapshot bhejiye", "naya snapshot", "title: \"Reading session\""],
  },
  {
    name: "Reader Arena profile card and ranking screen",
    entryId: "reader-arena",
    files: ["App.jsx", "ReaderArena.jsx", "ReaderArenaEntry.jsx", "ReaderArena.css"],
    includes: ["const ReaderArena = lazy", "id=\"arena-tab-weekly\"", "id=\"arena-tab-all_time\"", "layoutId={`arena-reader-${reader.key}`}", "formatWeekCountdown", "triggerLightTap(); onOpen()"],
  },
  {
    name: "push prompt banner",
    entryId: "notifications",
    files: ["PushPrompt.jsx"],
    includes: ["Stay in the loop", "Turn on", "Notifications are blocked"],
  },
  {
    name: "gem card studio and chat diagram",
    entryId: "gem-detail",
    files: ["GemStoryCard.jsx", "gemTemplates/index.js", "helpAnimations.js", "HelpAnimations.jsx"],
    includes: ["Choose gem card template", "Surprise me", "Export aspect ratio", "id: \"gem-download\"", "Choose a template", "kind: \"flow\""],
  },
  {
    name: "updates and release notes screen",
    entryId: "updates",
    files: ["SettingsScreens.jsx"],
    includes: ["Check for updates", "Version & release notes", "See what’s new in Reading Companion"],
  },
  {
    name: "Reader Arena release card",
    entryId: "release-2-4-0",
    files: ["SettingsScreens.jsx", "ReaderArenaReleaseCard.jsx", "ReaderArenaReleaseCard.css", "../public/release-notes.json"],
    includes: ["release.arena ? <ReaderArenaReleaseCard release={release} />", "arena-release-crown", "prefers-reduced-motion: reduce", "Reader Arena & Honest Eyes"],
  },
  {
    name: "Gem Studio 2.5.0 release card",
    entryId: "release-2-5-0",
    files: ["ReaderArenaReleaseCard.jsx", "ReaderArenaReleaseCard.css", "../public/release-notes.json"],
    includes: ["release.gemStudio", "Gem Studio release", "studio-gem-orbit", "studio-release-sheen", "Every Line, Reimagined"],
  },
  {
    name: "report issue workflow",
    entryId: "report-issue",
    files: ["SettingsScreens.jsx", "ReportsView.jsx"],
    includes: ["Raise an issue", "Improve with AI", "Use suggestion", "Keep mine", "Your reports", "Status timeline"],
  },
  {
    name: "help privacy request payload",
    entryId: "help-privacy",
    files: ["HelpGuideScreen.jsx"],
    includes: ["question: text", "history", "checkNewUser"],
  },
  {
    name: "welcome tour setup",
    entryId: "onboarding",
    files: ["onboarding/Onboarding.jsx"],
    includes: ["Skip", "Tumhara naam", "Tumhe kaunsi books pasand hain?", "Roz kitni der padhna chahoge?"],
  },
  {
    name: "about screen",
    entryId: "about",
    files: ["AboutScreen.jsx"],
    includes: ["Why it exists", "The developer", "Built with"],
  },
];

export const HELP_KNOWLEDGE_BAN_PATTERNS = [
  /docsaccesscard/i,
  /docs_owner_user_ids/i,
  /hidden developer docs/i,
  /\bin-app docs\b/i,
  /\b7-tap unlock\b/i,
  /\bseven-tap unlock\b/i,
  /docs diagrams/i,
  /docs narration/i,
];
